name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        uses: themm69/theos-action@main
        with:
          theos_sdks: https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
