name: CI
on:
  workflow_dispatch: # これを書くと手動ボタンが出ます
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: beerpiss/theos-action@v2.0.1
        with:
          theos_sdks: https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
